version: "3"

# sub-systems in containers
services:
  # hostapd
  # https://github.com/J-Siu/docker_hostapd/tree/master
  hostapd:
    container_name: hostapd
    image: jsiu/hostapd:latest
    network_mode: "host"
    privileged: true
    volumes:
      - .env/hostapd.conf:/hostapd.conf:ro
    restart: unless-stopped

  # pihole
  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: "host"
    environment:
      TZ: 'Australia/Sydney'
      WEBPASSWORD: '${PIHOLE_WEBPASSWORD}'
      INTERFACE: 'wlan0'
    # Volumes store your data between container upgrades
    volumes:
      - '.env/etc-pihole:/etc/pihole'
      - '.env/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

  # emqx MQTT broker
  emqx:
    container_name: emqx
    image: emqx/emqx:latest
    ports:
      - '1883:1883' # for MQTT
      - '8083:8083' # for MQTT over Websocket
      - '8883:8883' # for MQTT over SSL
      - '8084:8084' # for MQTT over Websocket/SSL
      - '18083:18083' # for the dashboard
    volumes:
      - '.env/emqx/etc:/opt/emqx/etc'
      - '.env/emqx/data:/opt/emqx/data'
      - '.env/emqx/log:/opt/emqx/log'
    restart: unless-stopped

  # InfluxDB
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - '.env/influxdb:/var/lib/influxdb'
    restart: unless-stopped

  # telegraf
  telegraf:
    container_name: telegraf
    image: telegraf:latest
    volumes:
      - '.env/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro'
    restart: unless-stopped

  # home-assistant
  # https://docs.linuxserver.io/images/docker-homeassistant/
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host # ui on port 8123
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Sydney/Australia
    volumes:
      - .env/homeassistant:/config
    restart: unless-stopped

  # Node-RED
  # https://nodered.org/docs/
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    group_add:
      - dialout
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0" # for zigbee2mqtt
    environment:
      - TZ=Sydney/Australia
    ports:
      - '1880:1880'
    volumes:
      - '.env/nodered:/data'
    restart: unless-stopped

  # heimdall to keep track of all the services
  heimdall:
    container_name: heimdall
    image: lscr.io/linuxserver/heimdall:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Sydney/Australia
    ports:
      # - '8080:80'
      - '8443:443'
    volumes:
      - '.env/heimdall:/config'
    restart: unless-stopped
